// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BaiThiNVA0025.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230629020037_Create_Table_NVAcau3")]
    partial class Create_Table_NVAcau3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("BaiThiNVA0025.Models.NVAcau3", b =>
                {
                    b.Property<string>("MaSinhVien")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneSinhVien")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenSinhVien")
                        .HasColumnType("TEXT");

                    b.HasKey("MaSinhVien");

                    b.ToTable("NVAcau3");
                });
#pragma warning restore 612, 618
        }
    }
}
